// Category
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"

// Brand
export const GET_ALL_BRANDS = "GET_ALL_BRANDS"
export const GET_ONE_BRAND = "GET_ONE_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"

// Subcategory
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
export const GET_SUBCATEGORY = "GET_SUBCATEGORY"

export const GET_ALL_SUBCATEGORIES = "GET_ALL_SUBCATEGORIES"

// Product
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"