// Category
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const GET_CATEGORY = "GET_CATEGORY"

// Brand
export const GET_ALL_BRANDS = "GET_ALL_BRANDS"
export const GET_BRAND = "GET_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"
export const UPDATE_BRAND = "UPDATE_BRAND"
export const DELETE_BRAND = "DELETE_BRAND"

// Subcategory
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
export const GET_SUBCATEGORY = "GET_SUBCATEGORY"
export const GET_SUBCATEGORIES_OF_CATEGORY = "GET_SUBCATEGORIES_OF_CATEGORY"
export const GET_ALL_SUBCATEGORIES = "GET_ALL_SUBCATEGORIES"
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY"
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"

// Product
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY"
export const GET_PRODUCTS_BY_CATEGORY_HOME = "GET_PRODUCTS_BY_CATEGORY_HOME"
export const GET_PRODUCTS_BY_BRAND = "GET_PRODUCT_BY_BRAND"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"

// Auth
export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const VERIFY_PASSWORD = "VERIFY_PASSWORD"
export const RESET_PASSWORD = "RESET_PASSWORD"

// ReviewCard
export const CREATE_REVIEW = "CREATE_REVIEW"
export const ALL_REVIEW_PRODUCT = "ALL_REVIEW_PRODUCT"
export const DELETE_REVIEW = "DELETE_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"

// Wishlist
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"
export const USER_WISHLIST = "USER_WISHLIST"

// Coupon
export const ADD_COUPON = "ADD_COUPON"
export const GET_ALL_COUPONS = "GET_ALL_COUPONS"
export const DELETE_COUPON = "DELETE_COUPON"
export const GET_ONE_COUPON = "GET_ONE_COUPON"
export const EDIT_COUPON = "EDIT_COUPON"

// User Profile
export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS"
export const GET_ALL_USER_ADDRESSES = "GET_ALL_USER_ADDRESS"
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS"
export const GET_ONE_USER_ADDRESS = "GET_ONE_USER_ADDRESS"
export const EDIT_USER_ADDRESS = "EDIT_USER_ADDRESS"
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"

// Cart
export const ADD_TO_CART = "ADD_TO_CART"
export const GET_USER_CART = "GET_USER_CART"
export const CLEAR_USER_CART = "CLEAR_USER_CART"
export const UPDATE_ITEM_IN_CART = "UPDATE_ITEM_IN_CART"
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART"
export const APPLY_CART_COUPON = "APPLY_CART_COUPON"

// ORDER
export const CREATE_CASH_ORDER = "CREATE_CASH_ORDER"
export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_ONE_ORDER = "GET_ONE_ORDER"
export const UPDATE_ORDER_PAY = "UPDATE_ORDER_PAY"
export const UPDATE_ORDER_DELIVER = "UPDATE_ORDER_DELIVER"
export const CREATE_ORDER_ONLINE = "CREATE_ORDER_ONLINE"

export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_USER = "GET_USER"
export const UPDATE_USER = "UPDATE_USER"
export const CREATE_USER = "CREATE_USER"
export const DELETE_USER = "DELETE_USER"

// SEARCH

export const UPDATE_SEARCH_PARAMS = "UPDATE_SEARCH_PARAMS";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";